# Generated by Django 4.1.1 on 2022-10-04 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 17, 2, 59, 282172)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 4, 17, 2, 59, 248122)),
        ),
    ]
